/* Generated By:JavaCC: Do not edit this line. SimpleCSVConstants.java */
package org.xerial.util.impl;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SimpleCSVConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMMA = 1;
  /** RegularExpression Id. */
  int ELEMENT = 2;
  /** RegularExpression Id. */
  int STRING = 3;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\",\"",
    "<ELEMENT>",
    "<STRING>",
  };

}
